# -*- coding: utf-8 -*-
"""SmartResume_NLP_Project_FINALL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rt5t6jetX6TinBU13lcWn_AM1IwyxiTT

# SmartResume: An NLP-Based Resume–Job Matching and Skill Gap Analysis System

### Mini NLP Project

**Research Question:**  
How do traditional TF-IDF similarity and modern semantic embeddings differ when matching resumes with job descriptions?

### Project Overview
SmartResume compares a resume with a job description using:
- **TF-IDF + Cosine Similarity** as a traditional lexical baseline
- **Sentence Transformers** for semantic similarity
- A **hybrid score** combining both approaches
- **Rule-based skill gap analysis** to identify matching and missing skills
- A simple **match classification** and recommendation output

> **Important:** The dataset's `ai_match_score` is treated only as an auxiliary/reference score, not as verified ground truth.

## 1. Objectives

1. Preprocess resume and job-description text.
2. Measure lexical similarity using TF-IDF and cosine similarity.
3. Measure semantic similarity using a Sentence Transformer.
4. Compare traditional and semantic similarity scores.
5. Identify matching and missing skills.
6. Combine lexical and semantic scores into a hybrid score.
7. Classify resume–job compatibility into Strong, Moderate, or Low Match.
8. Evaluate the system using genuine and deliberately mismatched resume–job pairs.
9. Demonstrate the final SmartResume analyzer on a new resume and job description.
"""

# Install required packages in Google Colab
!pip install -q sentence-transformers

# Import libraries
import pandas as pd
import numpy as np
import re
import ast
import random
import matplotlib.pyplot as plt

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics import roc_auc_score

from sentence_transformers import SentenceTransformer

print("Libraries loaded successfully!")

"""## 2. Dataset

This project uses the **`/content/job_resume_fit.csv`** dataset from Hugging Face.

Expected Colab file path:

`/content/job_resume_fit.csv`

The dataset contains resume–job-description pairs and fields for job category, required skills, candidate skills, and several matching scores.

"""

# Load dataset
DATA_PATH = "/content/job_resume_fit.csv"

df = pd.read_csv(DATA_PATH)

print("Dataset loaded successfully!")
print("Shape:", df.shape)
display(df.head())

# Dataset information
print("Number of rows:", len(df))
print("Number of columns:", len(df.columns))
print("\nColumns:")
print(df.columns.tolist())

print("\nJob categories:", df["category"].nunique())
print("Categories:")
print(sorted(df["category"].dropna().unique().tolist()))

# Check missing values
missing_values = df.isnull().sum().sort_values(ascending=False)

print("Missing values by column:")
display(missing_values.to_frame("Missing Values"))

"""## 3. Text Preprocessing

The preprocessing pipeline:
1. Converts text to lowercase.
2. Removes punctuation and special characters.
3. Normalizes repeated whitespace.
4. Returns cleaned text for similarity calculations.

This is intentionally simple and explainable for a small NLP application.

"""

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'[^a-zA-Z0-9\s]', ' ', text)
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

df["clean_resume"] = df["resume_text"].apply(clean_text)
df["clean_job"] = df["job_text"].apply(clean_text)

print("Preprocessing completed!")

print("\nOriginal resume:")
print(df.loc[0, "resume_text"][:500])

print("\nCleaned resume:")
print(df.loc[0, "clean_resume"][:500])

"""## 4. Traditional NLP Baseline — TF-IDF

**TF-IDF (Term Frequency–Inverse Document Frequency)** represents text numerically based on the importance of words.

Cosine similarity is then used to measure the angle-based similarity between the resume and job-description vectors.

A higher score indicates greater lexical overlap.

"""

# Fit TF-IDF on all resumes and job descriptions together
tfidf_vectorizer = TfidfVectorizer(stop_words="english")

tfidf_matrix = tfidf_vectorizer.fit_transform(
    pd.concat([df["clean_resume"], df["clean_job"]], ignore_index=True)
)

resume_vectors = tfidf_matrix[:len(df)]
job_vectors = tfidf_matrix[len(df):]

tfidf_scores = []

for i in range(len(df)):
    score = cosine_similarity(
        resume_vectors[i],
        job_vectors[i]
    )[0][0]
    tfidf_scores.append(score * 100)

df["tfidf_match_score"] = np.array(tfidf_scores)

print("TF-IDF similarity calculation completed!")

# TF-IDF statistics
print("TF-IDF Match Score Statistics")
print("-----------------------------")
print(f"Average: {df['tfidf_match_score'].mean():.2f}%")
print(f"Median:  {df['tfidf_match_score'].median():.2f}%")
print(f"Minimum: {df['tfidf_match_score'].min():.2f}%")
print(f"Maximum: {df['tfidf_match_score'].max():.2f}%")

# TF-IDF score distribution
plt.figure(figsize=(8, 5))
plt.hist(df["tfidf_match_score"], bins=20)
plt.xlabel("TF-IDF Match Score (%)")
plt.ylabel("Number of Resume-JD Pairs")
plt.title("Distribution of TF-IDF Resume–Job Match Scores")
plt.tight_layout()
plt.show()

"""## 5. Semantic NLP — Sentence Transformers

The project uses the pretrained **`all-MiniLM-L6-v2`** Sentence Transformer.

Unlike TF-IDF, sentence embeddings represent text in a semantic vector space. This allows the system to recognize related meaning even when the exact words are different.

The model is used only for generating embeddings; no supervised training is performed in this project.

"""

# Load Sentence Transformer
model = SentenceTransformer("all-MiniLM-L6-v2")

print("Sentence Transformer loaded successfully!")

# Generate embeddings
resume_embeddings = model.encode(
    df["clean_resume"].tolist(),
    show_progress_bar=True
)

job_embeddings = model.encode(
    df["clean_job"].tolist(),
    show_progress_bar=True
)

print("Resume embedding shape:", resume_embeddings.shape)
print("Job embedding shape:", job_embeddings.shape)

# Calculate semantic cosine similarity
semantic_scores = []

for i in range(len(df)):
    score = cosine_similarity(
        [resume_embeddings[i]],
        [job_embeddings[i]]
    )[0][0]
    semantic_scores.append(score * 100)

df["semantic_match_score"] = np.array(semantic_scores)

print("Semantic similarity calculation completed!")

# Compare similarity methods
comparison = df[
    [
        "category",
        "tfidf_match_score",
        "semantic_match_score",
        "ai_match_score"
    ]
].copy()

display(comparison.head(10))

print("Average TF-IDF Score:",
      round(df["tfidf_match_score"].mean(), 2))

print("Average Semantic Score:",
      round(df["semantic_match_score"].mean(), 2))

print("Average Dataset AI Reference Score:",
      round(df["ai_match_score"].mean(), 2))

# Correlation analysis
correlation = df[
    [
        "tfidf_match_score",
        "semantic_match_score",
        "ai_match_score"
    ]
].corr()

display(correlation)

# TF-IDF vs Semantic Similarity
plt.figure(figsize=(9, 5))
plt.scatter(
    df["tfidf_match_score"],
    df["semantic_match_score"],
    alpha=0.5
)
plt.xlabel("TF-IDF Match Score (%)")
plt.ylabel("Semantic Match Score (%)")
plt.title("TF-IDF vs Semantic Similarity")
plt.tight_layout()
plt.show()

"""## 6. Skill Gap Analysis

The dataset provides:
- `job_required_skills`
- `resume_skill_list`

The lists are parsed and compared using set intersection and set difference.

- **Matching skills** = required skills also present in the resume skill list
- **Missing skills** = required skills absent from the resume skill list

"""

def parse_skills(skill_text):
    try:
        skills = ast.literal_eval(skill_text)
        if isinstance(skills, (list, tuple, set)):
            return set(str(skill).lower().strip() for skill in skills)
    except Exception:
        pass
    return set()

df["required_skills"] = df["job_required_skills"].apply(parse_skills)
df["candidate_skills"] = df["resume_skill_list"].apply(parse_skills)

def find_skill_gaps(row):
    required = row["required_skills"]
    candidate = row["candidate_skills"]

    matching = required.intersection(candidate)
    missing = required.difference(candidate)

    return pd.Series({
        "matching_skills": sorted(matching),
        "missing_skills": sorted(missing)
    })

df[["matching_skills", "missing_skills"]] = df.apply(
    find_skill_gaps,
    axis=1
)

def skill_match_percentage(row):
    required = row["required_skills"]
    matching = row["matching_skills"]

    if len(required) == 0:
        return 0.0

    return (len(matching) / len(required)) * 100

df["skill_match_percentage"] = df.apply(
    skill_match_percentage,
    axis=1
)

print("Skill gap analysis completed!")

# Example skill-gap analysis
row = df.iloc[0]

print("JOB CATEGORY:")
print(row["category"])

print("\nREQUIRED SKILLS:")
print(row["required_skills"])

print("\nCANDIDATE SKILLS:")
print(row["candidate_skills"])

print("\nMATCHING SKILLS:")
print(row["matching_skills"])

print("\nMISSING SKILLS:")
print(row["missing_skills"])

print(f"\nSkill Match Percentage: {row['skill_match_percentage']:.2f}%")

"""## 7. Hybrid Resume–Job Matching

To combine the strengths of both approaches:

**Hybrid Score = 0.4 × TF-IDF Score + 0.6 × Semantic Score**

The semantic component receives a larger weight because it captures contextual similarity, while TF-IDF provides a transparent lexical baseline.

The weights are a **heuristic design choice**, not learned optimal weights.

"""

# Hybrid score
df["hybrid_match_score"] = (
    0.4 * df["tfidf_match_score"] +
    0.6 * df["semantic_match_score"]
)

def classify_match(score):
    if score >= 70:
        return "Strong Match"
    elif score >= 45:
        return "Moderate Match"
    else:
        return "Low Match"

df["match_category"] = df["hybrid_match_score"].apply(classify_match)

print("Hybrid scoring completed!")

# Final results table
final_results = df[
    [
        "category",
        "tfidf_match_score",
        "semantic_match_score",
        "hybrid_match_score",
        "skill_match_percentage",
        "match_category"
    ]
].copy()

final_results.columns = [
    "Job Category",
    "TF-IDF Score (%)",
    "Semantic Score (%)",
    "Hybrid Score (%)",
    "Skill Match (%)",
    "Result"
]

display(final_results.head(10))

"""## 8. Evaluation — Genuine vs Controlled Mismatched Pairs

The dataset does not provide independently verified human relevance labels, so we do not claim classification accuracy against a ground-truth relevance label.

Instead, we perform a **controlled pairwise evaluation**:

- **Positive pair:** the original resume and its associated job description.
- **Negative pair:** the same resume paired with a job description from a **different job category**.

The mismatched pairs are automatically constructed for experimental comparison. They should be interpreted as controlled negatives, not as human-verified judgments of relevance.

We calculate average similarity and ROC-AUC to compare how well TF-IDF and semantic similarity separate the genuine pairs from these deliberately mismatched pairs.


"""

# Create controlled mismatched pairs from different job categories
# Fixed seed makes the experiment reproducible.
rng = np.random.default_rng(42)

categories = df["category"].astype(str).values
all_indices = np.arange(len(df))
negative_job_indices = np.empty(len(df), dtype=int)

for i, category in enumerate(categories):
    candidates = all_indices[categories != category]
    negative_job_indices[i] = rng.choice(candidates)

negative_tfidf_scores = []
negative_semantic_scores = []

for i, j in enumerate(negative_job_indices):
    tfidf_score = cosine_similarity(
        resume_vectors[i],
        job_vectors[j]
    )[0][0] * 100

    semantic_score = cosine_similarity(
        [resume_embeddings[i]],
        [job_embeddings[j]]
    )[0][0] * 100

    negative_tfidf_scores.append(tfidf_score)
    negative_semantic_scores.append(semantic_score)

evaluation_df = pd.DataFrame({
    "label": [1] * len(df) + [0] * len(df),
    "pair_type": ["Genuine"] * len(df) + ["Different-category mismatch"] * len(df),
    "tfidf_score": (
        df["tfidf_match_score"].tolist() + negative_tfidf_scores
    ),
    "semantic_score": (
        df["semantic_match_score"].tolist() + negative_semantic_scores
    )
})

print("Evaluation pairs:", len(evaluation_df))
print("Positive pairs:", len(df))
print("Controlled negative pairs:", len(df))
display(evaluation_df.head())

# Positive vs negative score comparison
positive = evaluation_df[evaluation_df["label"] == 1]
negative = evaluation_df[evaluation_df["label"] == 0]

print("Average TF-IDF similarity")
print("  Genuine pairs:   ", round(positive["tfidf_score"].mean(), 2))
print("  Mismatched pairs:", round(negative["tfidf_score"].mean(), 2))

print("\nAverage Semantic similarity")
print("  Genuine pairs:   ", round(positive["semantic_score"].mean(), 2))
print("  Mismatched pairs:", round(negative["semantic_score"].mean(), 2))

# ROC-AUC evaluation
tfidf_auc = roc_auc_score(
    evaluation_df["label"],
    evaluation_df["tfidf_score"]
)

semantic_auc = roc_auc_score(
    evaluation_df["label"],
    evaluation_df["semantic_score"]
)

print(f"TF-IDF ROC-AUC: {tfidf_auc:.3f}")
print(f"Semantic ROC-AUC: {semantic_auc:.3f}")

# Visualize genuine vs mismatched scores
plt.figure(figsize=(9, 5))

plt.hist(
    positive["semantic_score"],
    bins=20,
    alpha=0.6,
    label="Genuine Pairs"
)

plt.hist(
    negative["semantic_score"],
    bins=20,
    alpha=0.6,
    label="Mismatched Pairs"
)

plt.xlabel("Semantic Similarity Score (%)")
plt.ylabel("Number of Pairs")
plt.title("Semantic Similarity: Genuine vs Mismatched Pairs")
plt.legend()
plt.tight_layout()
plt.show()

"""## 9. Multi-Pair Testing

The system is tested on several different resume–job pairs rather than relying on a single example.

"""

test_indices = [0, 10, 20, 30, 40, 50, 60, 70, 80, 90]

test_results = []

for i in test_indices:
    test_results.append({
        "Index": i,
        "Category": df.loc[i, "category"],
        "TF-IDF (%)": round(df.loc[i, "tfidf_match_score"], 2),
        "Semantic (%)": round(df.loc[i, "semantic_match_score"], 2),
        "Hybrid (%)": round(df.loc[i, "hybrid_match_score"], 2),
        "Skill Match (%)": round(df.loc[i, "skill_match_percentage"], 2),
        "Result": df.loc[i, "match_category"]
    })

test_df = pd.DataFrame(test_results)
display(test_df)

# Match-category distribution
match_distribution = df["match_category"].value_counts()

print(match_distribution)

plt.figure(figsize=(7, 5))
match_distribution.plot(kind="bar")
plt.xlabel("Match Category")
plt.ylabel("Number of Resume-JD Pairs")
plt.title("Distribution of Resume–Job Match Categories")
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

# Skill-match statistics
print("Skill Match Statistics")
print("----------------------")
print(f"Average Skill Match: {df['skill_match_percentage'].mean():.2f}%")
print(f"Highest Skill Match: {df['skill_match_percentage'].max():.2f}%")
print(f"Lowest Skill Match: {df['skill_match_percentage'].min():.2f}%")

"""## 10. Category-Level Analysis

The following table and graph show the average similarity scores across job categories.

"""

category_results = df.groupby("category")[
    [
        "tfidf_match_score",
        "semantic_match_score",
        "hybrid_match_score",
        "skill_match_percentage"
    ]
].mean().sort_values(
    "hybrid_match_score",
    ascending=False
)

display(category_results)

plt.figure(figsize=(10, 6))
category_results["hybrid_match_score"].plot(kind="bar")
plt.xlabel("Job Category")
plt.ylabel("Average Hybrid Match Score (%)")
plt.title("Average Resume–Job Match Score by Category")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()

"""## 11. Interesting Case Study

This finds a pair where semantic similarity is substantially higher than TF-IDF similarity.

Such cases illustrate how semantic embeddings can capture related meaning even when the exact vocabulary differs.

"""

df["semantic_tfidf_difference"] = (
    df["semantic_match_score"] -
    df["tfidf_match_score"]
)

interesting_index = df["semantic_tfidf_difference"].idxmax()
interesting_case = df.loc[interesting_index]

print("Category:", interesting_case["category"])
print("TF-IDF Score:", round(interesting_case["tfidf_match_score"], 2))
print("Semantic Score:", round(interesting_case["semantic_match_score"], 2))
print(
    "Difference:",
    round(interesting_case["semantic_tfidf_difference"], 2)
)

"""## 12. Reference-Score Comparison

The dataset contains an `ai_match_score`. Because this score is already supplied by the dataset and is not independently verified, it is treated only as a **reference/auxiliary comparison**, not as ground truth.

This section helps investigate whether the project's hybrid score behaves similarly to the dataset's existing AI-based score.

"""

reference_corr = df[
    ["hybrid_match_score", "ai_match_score"]
].corr().iloc[0, 1]

print(
    f"Correlation between Hybrid Score and Dataset AI Reference Score: "
    f"{reference_corr:.3f}"
)

"""## 13. Final SmartResume Application Function

The function below turns the project into a reusable mini application.

For a new resume and job description, it:
1. Cleans the text.
2. Computes TF-IDF similarity.
3. Computes semantic similarity.
4. Calculates the hybrid score.
5. Extracts skills using a dataset-derived vocabulary supplemented with common technical skills.
6. Reports matching and missing skills.
7. Produces a simple recommendation.

**Note:** Skill extraction is rule-based. It depends on the selected vocabulary and may miss synonyms or skills that are not represented in that vocabulary.

"""

# Corrected SmartResume application function
# This version uses a clean technical-skill vocabulary to avoid
# false matches such as "analyst", "analysis", "learning", and "A+".

application_skills = {
    "python", "sql", "pandas", "numpy", "scikit-learn",
    "machine learning", "deep learning", "natural language processing",
    "nlp", "data analysis", "data preprocessing", "data visualization",
    "statistical analysis", "statistics", "excel", "power bi",
    "tensorflow", "pytorch", "java", "c++", "javascript",
    "html", "css", "flask", "django", "node.js", "react",
    "mysql", "mongodb", "git", "github", "tableau",
    "communication", "problem solving", "teamwork"
}

skill_vocabulary = sorted(application_skills)


def extract_skills_from_text(text, vocabulary):
    """Extract technical skills using complete phrase matching."""
    cleaned = clean_text(text)
    found = set()

    for skill in vocabulary:
        skill_clean = clean_text(skill)

        if not skill_clean:
            continue

        pattern = r"(?<!\w)" + re.escape(skill_clean) + r"(?!\w)"

        if re.search(pattern, cleaned):
            found.add(skill)

    return found


def smart_resume_analysis(resume_text, job_text):
    """Analyze a resume against a job description."""

    clean_resume = clean_text(resume_text)
    clean_job = clean_text(job_text)

    # TF-IDF using the already-fitted dataset vectorizer
    input_vectors = tfidf_vectorizer.transform(
        [clean_resume, clean_job]
    )

    tfidf_score = cosine_similarity(
        input_vectors[0],
        input_vectors[1]
    )[0][0] * 100

    # Semantic similarity
    resume_embedding = model.encode([clean_resume])
    job_embedding = model.encode([clean_job])

    semantic_score = cosine_similarity(
        resume_embedding,
        job_embedding
    )[0][0] * 100

    # Hybrid score
    hybrid_score = (
        0.4 * tfidf_score +
        0.6 * semantic_score
    )

    # Skill-gap analysis
    required_skills = extract_skills_from_text(
        job_text,
        skill_vocabulary
    )

    candidate_skills = extract_skills_from_text(
        resume_text,
        skill_vocabulary
    )

    matching_skills = required_skills.intersection(
        candidate_skills
    )

    missing_skills = required_skills.difference(
        candidate_skills
    )

    skill_match = (
        (len(matching_skills) / len(required_skills)) * 100
        if required_skills else 0.0
    )

    result = classify_match(hybrid_score)

    if missing_skills:
        recommendations = [
            f"Consider improving or gaining experience in: {skill}."
            for skill in sorted(missing_skills)[:5]
        ]
    else:
        recommendations = [
            "No major skill gaps were detected from the selected skill vocabulary."
        ]

    return {
        "TF-IDF Score (%)": round(tfidf_score, 2),
        "Semantic Score (%)": round(semantic_score, 2),
        "Hybrid Match Score (%)": round(hybrid_score, 2),
        "Overall Result": result,
        "Matching Skills": sorted(matching_skills),
        "Missing Skills": sorted(missing_skills),
        "Skill Match (%)": round(skill_match, 2),
        "Recommendations": recommendations
    }


print("SmartResume analyzer is ready!")
print("Number of skills in application vocabulary:", len(skill_vocabulary))

"""## 14. Final Demo

The demonstration below applies SmartResume to a new resume and job description.

The output shows lexical similarity, semantic similarity, the hybrid match score, skill overlap, missing skills, and recommendations.

"""

# Final demonstration with a realistic resume and job description

sample_resume = """
BCA student with hands-on experience in Python, SQL, Pandas,
NumPy, scikit-learn, machine learning and NLP.
Completed academic projects involving data preprocessing,
data analysis and data visualization.
"""

sample_job = """
We are looking for a junior data analyst with skills in Python,
SQL, Pandas, machine learning and NLP.
The candidate should have knowledge of data preprocessing,
data visualization and statistical analysis.
"""

demo_result = smart_resume_analysis(sample_resume, sample_job)

print("SMARTRESUME ANALYSIS")
print("====================")
print(f"TF-IDF Score: {demo_result['TF-IDF Score (%)']}%")
print(f"Semantic Score: {demo_result['Semantic Score (%)']}%")
print(f"Hybrid Match Score: {demo_result['Hybrid Match Score (%)']}%")
print(f"Overall Result: {demo_result['Overall Result']}")
print(f"Skill Match: {demo_result['Skill Match (%)']}%")

print("\nMatching Skills:")
for skill in demo_result["Matching Skills"]:
    print("✓", skill)

print("\nMissing Skills:")
for skill in demo_result["Missing Skills"]:
    print("✗", skill)

print("\nRecommendations:")
for recommendation in demo_result["Recommendations"]:
    print("-", recommendation)

"""## 15. Results Summary

The main experimental observations should be reported using the values produced by the notebook.

### Metrics to report
- Average TF-IDF similarity
- Average semantic similarity
- TF-IDF vs semantic correlation
- Genuine vs mismatched average scores
- TF-IDF ROC-AUC
- Semantic ROC-AUC
- Hybrid/reference-score correlation
- Average skill-match percentage
- Distribution of Strong/Moderate/Low matches

### Interpretation
TF-IDF provides an interpretable lexical baseline, while Sentence Transformer embeddings provide a semantic representation. The hybrid score combines both signals. Skill-gap analysis adds an explainable layer by showing which required skills are present or absent.

Do **not** describe the dataset's `ai_match_score` as ground truth.

## 16. Limitations

1. The dataset does not provide independently verified human relevance labels.
2. The hybrid weights (40% TF-IDF and 60% semantic) are heuristic rather than learned.
3. The Strong/Moderate/Low thresholds are heuristic.
4. Rule-based skill extraction depends on the dataset-derived vocabulary.
5. Synonyms and equivalent skill phrases may not always be detected.
6. Sentence Transformer inference can be slower than TF-IDF.
7. The system does not assess candidate experience quality, seniority, achievements, or context beyond the supplied text.
8. The reference `ai_match_score` comes from the dataset and should not be treated as ground truth.

## 17. Future Scope

1. Train or calibrate the hybrid scoring weights using human-labeled resume–job relevance data.
2. Add synonym and skill-ontology matching.
3. Extract skills using a trained NER model instead of only a rule-based vocabulary.
4. Support PDF/DOCX resume upload and automatic text extraction.
5. Add explainable highlighting of matched resume phrases.
6. Experiment with stronger domain-adapted transformer models.
7. Add a recruiter dashboard for ranking multiple candidates.
8. Add multilingual resume and job-description support.
9. Evaluate the system using a larger human-annotated benchmark.

## 18. Conclusion

SmartResume demonstrates an NLP-based approach to resume–job matching by comparing a traditional TF-IDF baseline with semantic sentence embeddings. The hybrid approach combines lexical overlap and contextual similarity, while skill-gap analysis provides an interpretable explanation of missing requirements.

The project also demonstrates that evaluating an NLP matching system requires care when a dataset lacks verified ground-truth relevance labels. Therefore, controlled genuine-versus-mismatched evaluation and auxiliary reference-score comparisons are used instead of unsupported accuracy claims.

Overall, the project combines classical NLP, modern semantic representation, similarity measurement, and explainable skill analysis in a small working application.
"""
